---

galaxy_info:
  author: Jiri Tyr
  description: Customizable Message Of The Day (motd)
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - system
dependencies: []
